echo starting virtual env...
cd /d "C:/Users/jerem/Documents/py/full-stack-e-commerce/backend/"
call .\venv\Scripts\activate
@echo venv ready. 
@echo Starting Uvicorn server...
uvicorn main:app --reload
@echo Server ready...